In [9]:
import tensorflow as tf


In [10]:
import numpy as np
import pandas as pd

In [11]:
dataframe = pd.read_csv("Churn_Modelling.csv")

In [12]:
dataframe.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [13]:
dataframe.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [14]:
dataframe.index

RangeIndex(start=0, stop=10000, step=1)

In [15]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [16]:
X = dataframe.iloc[:, 3:13].values

In [17]:
Y = dataframe.iloc[:, -1].values

In [18]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [19]:
Y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [20]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [21]:
labelE_X1 = LabelEncoder()


In [22]:
X[:,1] = labelE_X1.fit_transform(X[:,1])

In [23]:
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [24]:
labelE_X2 = LabelEncoder()
X[:,2] = labelE_X1.fit_transform(X[:,2])


In [25]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [26]:
Y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))



In [28]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [29]:
X = X[:,1:]

In [30]:
X

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [32]:
from sklearn.preprocessing import StandardScaler

In [33]:
sc = StandardScaler()

In [34]:
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

## Building the ANN

In [35]:
import keras

In [36]:
from tensorflow.keras.models import Sequential

In [37]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout

In [38]:
classifier = Sequential()

In [39]:
classifier.add(Dense(units = 6, activation =  'relu'))
classifier.add(Dropout(rate=0.1))

In [40]:
classifier.add(Dense(units = 6, activation =  'relu'))
classifier.add(Dropout(rate=0.1))

In [41]:
classifier.add(Dense(units = 1, activation =  'sigmoid'))

In [42]:
classifier.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [35]:
classifier.fit(X_train, Y_train, batch_size=10, epochs=100)

Epoch 1/100
800/800 [==============================] - 6s 2ms/step - loss: 0.7468 - accuracy: 0.5256
Epoch 2/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4624 - accuracy: 0.8013: 
Epoch 3/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4348 - accuracy: 0.8077
Epoch 4/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4252 - accuracy: 0.8107
Epoch 5/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4206 - accuracy: 0.8214
Epoch 6/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4136 - accuracy: 0.8225
Epoch 7/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4114 - accuracy: 0.8255
Epoch 8/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4061 - accuracy: 0.8341
Epoch 9/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3912 - accuracy: 0.8398: 0s - l
Epoch 10/100
800/800 [==============================] - 1s 2ms/step - loss: 0.396

In [36]:
y_pred = classifier.predict(X_test)

In [37]:
y_pred

array([[0.22108123],
       [0.2549751 ],
       [0.13972229],
       ...,
       [0.17717648],
       [0.1091207 ],
       [0.15686473]], dtype=float32)

In [38]:
y_pred = (y_pred>0.5)

In [39]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [41]:
pred = confusion_matrix(Y_test, y_pred)

In [42]:
pred

array([[1530,   65],
       [ 217,  188]], dtype=int64)

In [43]:
accuracy_score(Y_test, y_pred)

0.859

## Hyperparameter tuning

In [43]:
from keras.wrappers.scikit_learn import KerasClassifier

In [44]:
from sklearn.model_selection import GridSearchCV

In [45]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [56]:
def build_classifier(optimizer = 'adam'):
    classifier = Sequential()
    classifier.add(Dense(units = 6, activation =  'relu'))
    classifier.add(Dense(units = 6, activation =  'relu'))
    classifier.add(Dense(units = 1, activation =  'sigmoid'))
    classifier.compile(optimizer=optimizer, loss = 'binary_crossentropy', metrics=['accuracy'])
    return classifier


In [57]:
classifier = KerasClassifier(build_fn = build_classifier)

In [61]:
parameters = {'batch_size': [25, 32], 'epochs' : [100,500], 'optimizer':['adam','rmsprop']}

In [62]:
grid_search = GridSearchCV(estimator = classifier, param_grid = parameters, scoring = 'accuracy', cv = 10)

In [63]:
grid_search = grid_search.fit(X_train, Y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

Epoch 1/100
288/288 [==============================] - 4s 1ms/step - loss: 0.5815 - accuracy: 0.7413
Epoch 2/100
288/288 [==============================] - 0s 990us/step - loss: 0.4691 - accuracy: 0.7908
Epoch 3/100
288/288 [==============================] - 0s 1ms/step - loss: 0.4411 - accuracy: 0.7999
Epoch 4/100
288/288 [==============================] - 0s 1ms/step - loss: 0.4250 - accuracy: 0.8009
Epoch 5/100
288/288 [==============================] - 0s 983us/step - loss: 0.4276 - accuracy: 0.8070
Epoch 6/100
288/288 [==============================] - 0s 987us/step - loss: 0.4110 - accuracy: 0.8167
Epoch 7/100
288/288 [==============================] - 0s 1ms/step - loss: 0.4085 - accuracy: 0.8158
Epoch 8/100
288/288 [==============================] - 0s 1ms/step - loss: 0.3983 - accuracy: 0.8268
Epoch 9/100
288/288 [==============================] - 0s 1ms/step - loss: 0.3968 - accuracy: 0.8302
Epoch 10/100
288/288 [==============================] - 0s 1ms/step - loss: 0.3919 - 

In [64]:
best_accuracy

0.860625

In [65]:
best_parameters

{'batch_size': 25, 'epochs': 500, 'optimizer': 'adam'}